# https://kitsu.cg-wire.com/installation/#self-hosting
# https://zou.cg-wire.com/

services:
  kitsu-10-2:
    container_name: kitsu-10-2
    hostname: kitsu-10-2
    domainname: farm.evil
    build:
      context: .
      dockerfile: Dockerfile
      target: kitsu
    restart: always
    ports:
      - "${KITSU_PORT_HOST}:${KITSU_PORT_CONTAINER}"
      - "5432:5432"  # What's that for ?
    volumes:
      - ./postgres/postgresql.conf:/etc/postgresql/14/main/postgresql.conf:ro
      - ${NFS_ENTRY_POINT}:${NFS_ENTRY_POINT}
      - ${NFS_ENTRY_POINT}:${NFS_ENTRY_POINT_LNS}
#      - ${NFS_ENTRY_POINT_LNS}/test_data/10.2/kitsu/var/lib/postgresql:/var/lib/postgresql
#      - /data/share/kitsu/database:/var/lib/pgsql
# cp -r /var/lib/postgresql/14 ${NFS_ENTRY_POINT_LNS}/test_data/10.2/kitsu/
# drwxr-xr-x 3 postgres postgres  4096 Dec 20 01:06 postgresql/
# drwx------ 2 root     root      4096 Dec  2 13:36 private/
# drwxr-xr-x 2 root     root      4096 Dec  2 13:36 python/
# drwxr-x--- 2 redis    redis     4096 Dec  2 13:37 redis/
# -rw-r--r-- 1 root     root     12288 Dec 20 01:06 sendria.sqlite
# -rw-r--r-- 1 root     root         0 Sep 11 14:04 shells.state
# drwxr-xr-x 1 root     root      4096 Dec  2 13:37 systemd/
# drwxr-xr-x 3 root     root      4096 Dec  2 13:37 ucf/
# root@kitsu-10-2:/var/lib# id -u postgres
# 105