__all__ = [
    "COMPOSE_SCOPE_GROUP_PREFIX",
    "ATTACH_PANGOLIN_SITE_TO_COMPOSE_SCOPE",
    "ATTACH_GRAFANA_ALLOY_TO_COMPOSE_SCOPE"
]

import os

COMPOSE_SCOPE_GROUP_PREFIX = "ComposeScope"

ATTACH_PANGOLIN_SITE_TO_COMPOSE_SCOPE = bool(
    int(
        os.environ.get("OPENSTUDIOLANDSCAPES__ATTACH_PANGOLIN_SITE_TO_COMPOSE_SCOPE", 0)
    )
)

ATTACH_GRAFANA_ALLOY_TO_COMPOSE_SCOPE = bool(
    int(
        os.environ.get("OPENSTUDIOLANDSCAPES__ATTACH_GRAFANA_ALLOY_TO_COMPOSE_SCOPE", 0)
    )
)
