[build-system]
requires = [
    "setuptools>=80",
    "setuptools-scm>=9",
]
build-backend = "setuptools.build_meta"

[project]
requires-python = ">=3.11"
description = "A Toolkit to create dynamic Animation and VFX studio environments for robust automation and pipelines."
name = "OpenStudioLandscapes"
license-files = [
    "LICENSE.txt",
]
classifiers = [
    "Programming Language :: Python",
    "Framework :: OpenStudioLandscapes",
    "Development Status :: 4 - Beta",
]
dependencies = [
    "snakemd",
    "pydot",
    "nox",
    "importlib-metadata; python_version<\"3.8\"",
    "gitpython",
    "docker-compose-graph @ git+https://github.com/michimussato/docker-compose-graph.git@v1.0.0",
    "docker",
    "dagster==1.9.11",
    "dagster-postgres",
    "PyYAML",
    "OpenStudioLandscapesUtil-HarborCLI @ git+https://github.com/michimussato/OpenStudioLandscapesUtil-HarborCLI.git@v1.8.0-rc1",
]
dynamic = [
    "version",
]
authors = [
    { email = "michimussato@gmail.com", name = "Michael Mussato" },
]
maintainers = [
    { email = "michimussato@gmail.com", name = "Michael Mussato" },
]

[project.urls]
Homepage = "https://github.com/michimussato/OpenStudioLandscapes"

[project.readme]
file = "README.md"
content-type = "text/markdown; charset=UTF-8"

[project.optional-dependencies]
readme = [
    "OpenStudioLandscapesUtil-ReadmeGenerator @ git+https://github.com/michimussato/OpenStudioLandscapesUtil-ReadmeGenerator.git@v1.8.0-rc1",
]
sbom = [
    "cyclonedx-bom",
    "OpenStudioLandscapes[graphviz]",
]
dev = [
    "dagster-webserver==1.9.11",
    "OpenStudioLandscapes[testing]",
    "OpenStudioLandscapes[sbom]",
    "OpenStudioLandscapes[readme]",
    "OpenStudioLandscapes[nox]",
    "OpenStudioLandscapes[lint]",
    "OpenStudioLandscapes[coverage]",
    "OpenStudioLandscapesUtil-VersionBumper @ git+https://github.com/michimussato/OpenStudioLandscapesUtil-VersionBumper.git",
]
dagster_mysql = [
    "dagster==1.9.11",
    "dagster-webserver==1.9.11",
    "OpenStudioLandscapes[nox]",
]
dagster_postgres = [
    "dagster==1.9.11",
    "dagster-webserver==1.9.11",
    "dagster-postgres",
    "OpenStudioLandscapes[nox]",
]
nox = [
    "nox",
    "OpenStudioLandscapes[testing]",
]
graphviz = [
    "pipdeptree",
    "graphviz",
]
lint = [
    "pylint",
    "pre-commit",
    "isort",
    "black",
]
coverage = [
    "pytest",
    "coverage",
]
testing = [
    "setuptools",
    "pytest-cov",
    "pytest",
]

[project.entry-points]

[tool.setuptools]
include-package-data = true
platforms = [
    "Linux",
]

[tool.setuptools.packages.find]
namespaces = true
where = [
    "src",
]
exclude = [
    "tests",
]

[tool.dagster]
project_name = "OpenStudioLandscapes"
module_name = "OpenStudioLandscapes.engine.definitions"
