# mongodb-10-2            | Traceback (most recent call last):
# mongodb-10-2            |   File "/usr/local/bin/docker-entrypoint.py", line 637, in <module>
# mongodb-10-2            |     subprocess.run(get_final_command_line_args(), check=True)
# mongodb-10-2            |   File "/usr/lib/python3.8/subprocess.py", line 516, in run
# mongodb-10-2            |     raise CalledProcessError(retcode, process.args,
# mongodb-10-2            | subprocess.CalledProcessError: Command '['/usr/bin/mongod', '--dbpath', '/opt/Thinkbox/DeadlineDatabase10/mongo/data', '--bind_ip_all', '--noauth', '--storageEngine', 'wiredTiger', '--tlsMode', 'disabled']' returned non-zero exit status 100.
# mongodb-10-2 exited with code 1

## user mongodb has id 101

# data_NAMED
# test_data/opt/Thinkbox/DeadlineDatabase10/mongo/data_NAMED
#
# cd /var/lib/docker/volumes/102_mongo-data-10-2-test
# mv _data _data.bak
# cp -rf /home/michael/git/repos/deadline-setup/deadline-setup-docker/10.2/test_data/opt/Thinkbox/DeadlineDatabase10/mongo/data_NAMED _data
# chown -R 101:nobody _data
# - mongo-data-10-2-test:/opt/Thinkbox/DeadlineDatabase10/mongo/data


# data_LOCAL
# sudo chown -R 101:nobody test_data/opt/Thinkbox/DeadlineDatabase10/mongo/data_LOCAL
# - ./test_data/opt/Thinkbox/DeadlineDatabase10/mongo/data_NAMED:/opt/Thinkbox/DeadlineDatabase10/mongo/data


# DHCP
# https://github.com/devplayer0/docker-net-dhcp


# docker-compose build
# docker compose -f docker-compose.yaml build
# docker compose up


#include:
#  - path:
#      - ./docker-third-party/cgwire/docker-compose.kitsu.yaml
#  - path:
#      - ../repos/ayon-docker/docker-compose.yml
#      - ./docker-third-party/ayon/docker-compose.override.yml



services:
  mongo-express-10-2:
    container_name: mongo-express-10-2
    hostname: mongo-express-10-2
    domainname: ${ROOT_DOMAIN}
    depends_on:
      - mongodb-10-2
    # https://hub.docker.com/_/mongo-express
    # https://github.com/mongo-express/mongo-express
    image: mongo-express
    networks:
      - mongodb
    restart: always  # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    ports:
      - "${MONGO_EXPRESS_PORT_HOST}:${MONGO_EXPRESS_PORT_CONTAINER}"
    env_file:
      - .env
    volumes:
      - ${NFS_ENTRY_POINT}/test_data/10.2/opt/Thinkbox/DeadlineDatabase10/mongo/data_LOCAL:/opt/Thinkbox/DeadlineDatabase10/mongo/data
      # Read Only
      - ${NFS_ENTRY_POINT}:${NFS_ENTRY_POINT}:ro
      - ${NFS_ENTRY_POINT}:${NFS_ENTRY_POINT_LNS}:ro



  # https://github.com/hurlenko/filebrowser-docker
  # https://filebrowser.org/cli/filebrowser#options
  filebrowser:
    container_name: mongo-filebrowser-10-2
    hostname: mongo-filebrowser-10-2
    domainname: ${ROOT_DOMAIN}
    image: filebrowser/filebrowser
    restart: always
    env_file:
      - .env
    networks:
      - repository
    depends_on:
      - mongodb-10-2
    volumes:
      # By default, we already have a configuration file with some
      # defaults so you can just mount the root and the database.
      # Although you can overwrite by mounting a directory with a
      # new config file. If you don't already have a database file,
      # make sure to create a new empty file under the path you specified.
      # Otherwise, Docker will create an empty folder instead of an
      # empty file, resulting in an error when mounting the database
      - ./databases/filebrowser/filebrowser.db:/filebrowser.db
      - ./configs/filebrowser/filebrowser.json:/.filebrowser.json
      # Read Only
      - ${NFS_ENTRY_POINT}/test_data/10.2/opt/Thinkbox/DeadlineDatabase10/mongo/data_LOCAL:/opt/Thinkbox/DeadlineDatabase10/mongo/data:ro
#      - ${NFS_ENTRY_POINT_LNS}:${NFS_ENTRY_POINT_LNS}:ro
      - ${NFS_ENTRY_POINT}:${NFS_ENTRY_POINT}:ro
      - ${NFS_ENTRY_POINT}:${NFS_ENTRY_POINT_LNS}:ro
    ports:
      - "${FILEBROWSER_PORT_HOST}:${FILEBROWSER_PORT_CONTAINER}"



  mongodb-10-2:
    container_name: mongodb-10-2
    hostname: mongodb-10-2
    domainname: ${ROOT_DOMAIN}
    # https://hub.docker.com/layers/mongodb/mongodb-community-server/4.4-ubuntu2004/images/sha256-e2fd10d7979ee1c5565e5b37ad1ae62056dc5c0df8adb7fbff3b8a3409b55dad?context=explore
    image: mongodb/mongodb-community-server:4.4-ubuntu2004
    # https://docs.docker.com/reference/compose-file/services/#command
    networks:
      - mongodb
      - repository
    env_file:
      - .env
    command: >
      --dbpath /opt/Thinkbox/DeadlineDatabase10/mongo/data
      --bind_ip_all
      --noauth
      --storageEngine wiredTiger
      --tlsMode disabled
    ports:
      - "${MONGO_DB_PORT_HOST}:${MONGO_DB_PORT_CONTAINER}"
    volumes:
      - ${NFS_ENTRY_POINT}/test_data/10.2/opt/Thinkbox/DeadlineDatabase10/mongo/data_LOCAL:/opt/Thinkbox/DeadlineDatabase10/mongo/data
      # Read Only
      - ${NFS_ENTRY_POINT}:${NFS_ENTRY_POINT}:ro
      - ${NFS_ENTRY_POINT}:${NFS_ENTRY_POINT_LNS}:ro



  dagster_dev:
    env_file:
      - .env
    container_name: dagster-dev-10-2
    hostname: dagster-dev-10-2
    domainname: ${ROOT_DOMAIN}
    restart: always
    networks:
      - repository
      - mongodb
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dagster_dev
      args:
        - PYTHON_MAJ
        - PYTHON_MIN
        - PYTHON_PAT
    volumes:
      # By default, we already have a configuration file with some
      - ./configs/dagster_shared/workspace.yaml:/dagster/workspace.yaml:ro
      - ./configs/dagster_shared/dagster.yaml:/dagster/materializations/workspace.yaml:ro
      # - ${NFS_ENTRY_POINT}/test_data/10.2/opt/Thinkbox/DeadlineDatabase10/mongo/data_LOCAL:/opt/Thinkbox/DeadlineDatabase10/mongo/data:ro
#      - ${NFS_ENTRY_POINT_LNS}:${NFS_ENTRY_POINT_LNS}
      - ${NFS_ENTRY_POINT}:${NFS_ENTRY_POINT}
      - ${NFS_ENTRY_POINT}:${NFS_ENTRY_POINT_LNS}
    ports:
      - "${DAGSTER_DEV_PORT_HOST}:${DAGSTER_DEV_PORT_CONTAINER}"



#  likec4_dev:
#    container_name: likec4-dev-10-2
#    hostname: likec4-dev-10-2
#    domainname: ${ROOT_DOMAIN}
#    env_file:
#      - .env
#    restart: always
#    build:
#      context: .
#      dockerfile: ./Dockerfile
#      target: likec4_dev
#      args:
#        - PYTHON_MAJ
#        - PYTHON_MIN
#        - PYTHON_PAT
#    ports:
#      - "${LIKEC4_DEV_PORT_HOST}:${LIKEC4_DEV_PORT_CONTAINER}"



  deadline-repository-installer-10-2  :
    restart: "no"
    container_name: deadline-repository-installer-10-2
    hostname: deadline-repository-installer-10-2
    domainname: ${ROOT_DOMAIN}
    env_file:
      - .env
    depends_on:
      - mongodb-10-2
    networks:
      - mongodb
      - repository
    build:
      context: .
      dockerfile: ./Dockerfile
      target: repo_installer
      args:
        - PYTHON_MAJ
        - PYTHON_MIN
        - PYTHON_PAT
        - DEADLINE_VERSION
#        # args or environment?
        # https://stackoverflow.com/a/41919137/2207196
        - INSTALLERS_ROOT
    volumes:
#      - ./DeadlineRepositoryInstall:/opt/Thinkbox/DeadlineRepository10
      - ${NFS_ENTRY_POINT}/test_data/10.2/opt/Thinkbox/DeadlineRepository10:/opt/Thinkbox/DeadlineRepository10
      # Read Only
      - ${NFS_ENTRY_POINT}:${NFS_ENTRY_POINT}:ro
      - ${NFS_ENTRY_POINT}:${NFS_ENTRY_POINT_LNS}:ro



  deadline-client-installer-10-2:
    restart: "no"
    container_name: client-installer-10-2
    hostname: client-installer-10-2
    domainname: ${ROOT_DOMAIN}
    env_file:
      - .env
    depends_on:
      deadline-repository-installer-10-2:
        condition: service_completed_successfully
    networks:
      - mongodb
      - repository
    build:
      context: .
      dockerfile: ./Dockerfile
      target: client_installer
      args:
        - PYTHON_MAJ
        - PYTHON_MIN
        - PYTHON_PAT
        - DEADLINE_VERSION
        - INSTALLERS_ROOT
    volumes:
      - ${NFS_ENTRY_POINT}/test_data/10.2/opt/Thinkbox/Deadline10:/opt/Thinkbox/Deadline10
      - ${NFS_ENTRY_POINT}/test_data/10.2/opt/Thinkbox/DeadlineRepository10:/opt/Thinkbox/DeadlineRepository10
      # Read Only
      - ${NFS_ENTRY_POINT}:${NFS_ENTRY_POINT}:ro
      - ${NFS_ENTRY_POINT}:${NFS_ENTRY_POINT_LNS}:ro


  deadline-rcs-runner-10-2:
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - PYTHON_MAJ
        - PYTHON_MIN
        - PYTHON_PAT
        - DEADLINE_VERSION
        - INSTALLERS_ROOT
      target: rcs_runner
    container_name: rcs-runner-10-2
    hostname: rcs-runner-10-2
    domainname: ${ROOT_DOMAIN}
    depends_on:
      deadline-client-installer-10-2:
        condition: service_completed_successfully
    networks:
      - mongodb
      - repository
    volumes:
      # Config
      - ./configs/Deadline10/deadline.ini:/var/lib/Thinkbox/Deadline10/deadline.ini:ro
      # Data
      - ${NFS_ENTRY_POINT}/test_data/10.2/opt/Thinkbox/Deadline10:/opt/Thinkbox/Deadline10
      - ${NFS_ENTRY_POINT}/test_data/10.2/opt/Thinkbox/DeadlineRepository10:/opt/Thinkbox/DeadlineRepository10
      - ${NFS_ENTRY_POINT}:${NFS_ENTRY_POINT}:ro
      - ${NFS_ENTRY_POINT}:${NFS_ENTRY_POINT_LNS}:ro
#      - ./configs/Deadline10/cert/ca-certificates.crt:/var/lib/Thinkbox/Deadline10/cert/ca-certificates.crt:ro
    ports:
      - "${RCS_HTTP_PORT_HOST}:${RCS_HTTP_PORT_CONTAINER}"


  deadline-pulse-runner-10-2:
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - PYTHON_MAJ
        - PYTHON_MIN
        - PYTHON_PAT
        - DEADLINE_VERSION
        - INSTALLERS_ROOT
      target: pulse_runner
    container_name: pulse-runner-10-2
    hostname: pulse-runner-10-2
    domainname: ${ROOT_DOMAIN}
    depends_on:
      deadline-client-installer-10-2:
        condition: service_completed_successfully
      deadline-rcs-runner-10-2:
        condition: service_started
    networks:
      - mongodb
      - repository
    volumes:
      # Config
      - ./configs/Deadline10/deadline.ini:/var/lib/Thinkbox/Deadline10/deadline.ini:ro
      # Data
      - ${NFS_ENTRY_POINT}/test_data/10.2/opt/Thinkbox/Deadline10:/opt/Thinkbox/Deadline10
      - ${NFS_ENTRY_POINT}/test_data/10.2/opt/Thinkbox/DeadlineRepository10:/opt/Thinkbox/DeadlineRepository10
      - ${NFS_ENTRY_POINT}:${NFS_ENTRY_POINT}:ro
      - ${NFS_ENTRY_POINT}:${NFS_ENTRY_POINT_LNS}:ro
#      - ./configs/Deadline10/cert/ca-certificates.crt:/var/lib/Thinkbox/Deadline10/cert/ca-certificates.crt:ro
#    ports:
#      - "8888:8888"


  deadline-worker-runner-10-2:
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - PYTHON_MAJ
        - PYTHON_MIN
        - PYTHON_PAT
        - DEADLINE_VERSION
        - INSTALLERS_ROOT
      target: worker_runner
    container_name: worker-runner-10-2
    hostname: worker-runner-10-2
    domainname: ${ROOT_DOMAIN}
    depends_on:
      deadline-client-installer-10-2:
        condition: service_completed_successfully
      deadline-rcs-runner-10-2:
        condition: service_started
    networks:
      - mongodb
      - repository
    volumes:
      # Config
      - ./configs/Deadline10/deadline.ini:/var/lib/Thinkbox/Deadline10/deadline.ini:ro
      # Data
      - ${NFS_ENTRY_POINT}/test_data/10.2/opt/Thinkbox/Deadline10:/opt/Thinkbox/Deadline10
      - ${NFS_ENTRY_POINT}/test_data/10.2/opt/Thinkbox/DeadlineRepository10:/opt/Thinkbox/DeadlineRepository10
      - ${NFS_ENTRY_POINT}:${NFS_ENTRY_POINT}:ro
      - ${NFS_ENTRY_POINT}:${NFS_ENTRY_POINT_LNS}:ro
#      - ./configs/Deadline10/cert/ca-certificates.crt:/var/lib/Thinkbox/Deadline10/cert/ca-certificates.crt:ro
#    ports:
#      - "8888:8888"



  deadline-webservice-runner-10-2:
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - PYTHON_MAJ
        - PYTHON_MIN
        - PYTHON_PAT
        - DEADLINE_VERSION
        - INSTALLERS_ROOT
      target: webservice_runner
    container_name: webservice-runner-10-2
    hostname: webservice-runner-10-2
    domainname: ${ROOT_DOMAIN}
    depends_on:
      deadline-client-installer-10-2:
        condition: service_completed_successfully
      deadline-rcs-runner-10-2:
        condition: service_started
    networks:
      - mongodb
      - repository
    volumes:
      # Config
      - ./configs/Deadline10/deadline.ini:/var/lib/Thinkbox/Deadline10/deadline.ini:ro
      # Data
      - ${NFS_ENTRY_POINT}/test_data/10.2/opt/Thinkbox/Deadline10:/opt/Thinkbox/Deadline10
      - ${NFS_ENTRY_POINT}/test_data/10.2/opt/Thinkbox/DeadlineRepository10:/opt/Thinkbox/DeadlineRepository10
      - ${NFS_ENTRY_POINT}:${NFS_ENTRY_POINT}:ro
      - ${NFS_ENTRY_POINT}:${NFS_ENTRY_POINT_LNS}:ro
    ports:
      - "${WEBSERVICE_HTTP_PORT_HOST}:${WEBSERVICE_HTTP_PORT_CONTAINER}"



# https://www.warp.dev/terminus/docker-compose-networks
networks:
  mongodb:
    name: network_mongodb-10-2
  repository:
    name: network_repository-10-2
  ayon:
    name: network_ayon-10-2
