# mongodb-10-2            | Traceback (most recent call last):
# mongodb-10-2            |   File "/usr/local/bin/docker-entrypoint.py", line 637, in <module>
# mongodb-10-2            |     subprocess.run(get_final_command_line_args(), check=True)
# mongodb-10-2            |   File "/usr/lib/python3.8/subprocess.py", line 516, in run
# mongodb-10-2            |     raise CalledProcessError(retcode, process.args,
# mongodb-10-2            | subprocess.CalledProcessError: Command '['/usr/bin/mongod', '--dbpath', '/opt/Thinkbox/DeadlineDatabase10/mongo/data', '--bind_ip_all', '--noauth', '--storageEngine', 'wiredTiger', '--tlsMode', 'disabled']' returned non-zero exit status 100.
# mongodb-10-2 exited with code 1

## user mongodb has id 101

# data_NAMED
# test_data/opt/Thinkbox/DeadlineDatabase10/mongo/data_NAMED
#
# cd /var/lib/docker/volumes/102_mongo-data-10-2-test
# mv _data _data.bak
# cp -rf /home/michael/git/repos/deadline-setup/deadline-setup-docker/10.2/test_data/opt/Thinkbox/DeadlineDatabase10/mongo/data_NAMED _data
# chown -R 101:nobody _data
# - mongo-data-10-2-test:/opt/Thinkbox/DeadlineDatabase10/mongo/data


# data_LOCAL
# sudo chown -R 101:nobody test_data/opt/Thinkbox/DeadlineDatabase10/mongo/data_LOCAL
# - ./test_data/opt/Thinkbox/DeadlineDatabase10/mongo/data_NAMED:/opt/Thinkbox/DeadlineDatabase10/mongo/data


# DHCP
# https://github.com/devplayer0/docker-net-dhcp


# docker-compose build
# docker compose -f docker-compose.yaml build
# docker compose up


#include:
#  - path:
#      - docker-third-party/filebrowser/docker-compose.yaml
#  - path:
#      - docker-third-party/dagster/docker-compose.yaml
#  - path:
#      - docker-third-party/likec4/docker-compose.yaml
#  - path:
#      - docker-third-party/cgwire/docker-compose.kitsu.yaml
#  - path:
#      - ../repos/ayon-docker/docker-compose.yml
#      - docker-third-party/ayon/docker-compose.override.yml



services:

  deadline-rcs-runner-10-2:
    restart: always
    image: michimussato/generic_runner:latest
    command:
      - --executable
      - "/opt/Thinkbox/Deadline10/bin/deadlinercs"
    env_file:
      - .env
    container_name: rcs-runner-10-2
    hostname: rcs-runner-10-2
    domainname: ${ROOT_DOMAIN}
    depends_on:
      deadline-client-installer-10-2:
        condition: service_completed_successfully
    networks:
      - mongodb
      - repository
    volumes:
      # Config
      - ./configs/Deadline10/deadline.ini:/var/lib/Thinkbox/Deadline10/deadline.ini:ro
      # Data
      - ${NFS_ENTRY_POINT}/test_data/10.2/opt/Thinkbox/Deadline10:/opt/Thinkbox/Deadline10
      - ${NFS_ENTRY_POINT}/test_data/10.2/opt/Thinkbox/DeadlineRepository10:/opt/Thinkbox/DeadlineRepository10
      - ${NFS_ENTRY_POINT}:${NFS_ENTRY_POINT}:ro
      - ${NFS_ENTRY_POINT}:${NFS_ENTRY_POINT_LNS}:ro
#      - ./configs/Deadline10/cert/ca-certificates.crt:/var/lib/Thinkbox/Deadline10/cert/ca-certificates.crt:ro
    ports:
      - "${RCS_HTTP_PORT_HOST}:${RCS_HTTP_PORT_CONTAINER}"

  deadline-pulse-runner-10-2:
    restart: always
    image: michimussato/generic_runner:latest
    command:
      - --executable
      - "/opt/Thinkbox/Deadline10/bin/deadlinepulse"
      - --arguments
      - "['-nogui', '-nosplash']"
    container_name: pulse-runner-10-2
    hostname: pulse-runner-10-2
    domainname: ${ROOT_DOMAIN}
    depends_on:
      deadline-client-installer-10-2:
        condition: service_completed_successfully
      deadline-rcs-runner-10-2:
        condition: service_started
    networks:
      - mongodb
      - repository
    volumes:
      # Config
      - ./configs/Deadline10/deadline.ini:/var/lib/Thinkbox/Deadline10/deadline.ini:ro
      # Data
      - ${NFS_ENTRY_POINT}/test_data/10.2/opt/Thinkbox/Deadline10:/opt/Thinkbox/Deadline10
      - ${NFS_ENTRY_POINT}/test_data/10.2/opt/Thinkbox/DeadlineRepository10:/opt/Thinkbox/DeadlineRepository10
      - ${NFS_ENTRY_POINT}:${NFS_ENTRY_POINT}:ro
      - ${NFS_ENTRY_POINT}:${NFS_ENTRY_POINT_LNS}:ro
#      - ./configs/Deadline10/cert/ca-certificates.crt:/var/lib/Thinkbox/Deadline10/cert/ca-certificates.crt:ro
#    ports:
#      - "8888:8888"

  deadline-worker-runner-10-2:
    restart: always
    image: michimussato/generic_runner:latest
    command:
      - --executable
      - "/opt/Thinkbox/Deadline10/bin/deadlineworker"
      - --arguments
      - "['-nogui', '-nosplash']"
    env_file:
      - .env
    container_name: worker-runner-10-2
    hostname: worker-runner-10-2
    domainname: ${ROOT_DOMAIN}
    depends_on:
      deadline-client-installer-10-2:
        condition: service_completed_successfully
      deadline-rcs-runner-10-2:
        condition: service_started
    networks:
      - mongodb
      - repository
    volumes:
      # Config
      - ./configs/Deadline10/deadline.ini:/var/lib/Thinkbox/Deadline10/deadline.ini:ro
      # Data
      - ${NFS_ENTRY_POINT}/test_data/10.2/opt/Thinkbox/Deadline10:/opt/Thinkbox/Deadline10
      - ${NFS_ENTRY_POINT}/test_data/10.2/opt/Thinkbox/DeadlineRepository10:/opt/Thinkbox/DeadlineRepository10
      - ${NFS_ENTRY_POINT}:${NFS_ENTRY_POINT}:ro
      - ${NFS_ENTRY_POINT}:${NFS_ENTRY_POINT_LNS}:ro
#      - ./configs/Deadline10/cert/ca-certificates.crt:/var/lib/Thinkbox/Deadline10/cert/ca-certificates.crt:ro
#    ports:
#      - "8888:8888"

  deadline-webservice-runner-10-2:
    restart: always
    image: michimussato/generic_runner:latest
    command:
      - --executable
      - "/opt/Thinkbox/Deadline10/bin/deadlinewebservice"
    container_name: webservice-runner-10-2
    hostname: webservice-runner-10-2
    domainname: ${ROOT_DOMAIN}
    depends_on:
      deadline-client-installer-10-2:
        condition: service_completed_successfully
      deadline-rcs-runner-10-2:
        condition: service_started
    networks:
      - mongodb
      - repository
    volumes:
      # Config
      - ./configs/Deadline10/deadline.ini:/var/lib/Thinkbox/Deadline10/deadline.ini:ro
      # Data
      - ${NFS_ENTRY_POINT}/test_data/10.2/opt/Thinkbox/Deadline10:/opt/Thinkbox/Deadline10
      - ${NFS_ENTRY_POINT}/test_data/10.2/opt/Thinkbox/DeadlineRepository10:/opt/Thinkbox/DeadlineRepository10
      - ${NFS_ENTRY_POINT}:${NFS_ENTRY_POINT}:ro
      - ${NFS_ENTRY_POINT}:${NFS_ENTRY_POINT_LNS}:ro
    ports:
      - "${WEBSERVICE_HTTP_PORT_HOST}:${WEBSERVICE_HTTP_PORT_CONTAINER}"

# https://www.warp.dev/terminus/docker-compose-networks
networks:
  mongodb:
    name: network_mongodb-10-2
  repository:
    name: network_repository-10-2
  ayon:
    name: network_ayon-10-2
