%%{init: {'theme': 'default'}}%%
flowchart TB
  VtestdataoptThinkboxDeadlineDatabase10mongodataLOCAL{{"./test_data/opt/Thinkbox/DeadlineDatabase10/mongo/data_LOCAL"}} x-. /opt/Thinkbox/DeadlineDatabase10/mongo/data .-x mongodb102[mongodb-10-2]
  VtestdataoptThinkboxDeadlineDatabase10mongodataLOCAL x-. /opt/Thinkbox/DeadlineDatabase10/mongo/data .-x mongoexpress[mongo-express]
  VtestdataoptThinkboxDeadlineDatabase10mongodataLOCAL -. /opt/Thinkbox/DeadlineDatabase10/mongo/data .-x filebrowser
  Vnfs{{/nfs}} -. /nfs .-x filebrowser
  Vfilebrowserfilebrowserdb{{"./filebrowser/filebrowser.db"}} x-. "/filebrowser.db" .-x filebrowser
  Vfilebrowserfilebrowserjson{{"./filebrowser/filebrowser.json"}} x-. "/.filebrowser.json" .-x filebrowser
  Vdeadlineinstaller{{"./deadline_installer"}} -. /deadline_installer .-x deadlinerepositoryinstaller102[deadline-repository-installer-10-2]
  VDeadlineRepositoryInstall{{"./DeadlineRepositoryInstall"}} x-. /opt/Thinkbox/DeadlineRepository10 .-x deadlinerepositoryinstaller102
  Vdeadlineinstaller -. /deadline_installer .-x deadlinercsinstaller102[deadline-rcs-installer-10-2]
  VDeadlineRepositoryInstall x-. /opt/Thinkbox/DeadlineRepository10 .-x deadlinercsinstaller102
  VDeadlineClientInstall{{"./DeadlineClientInstall"}} x-. /opt/Thinkbox/Deadline10 .-x deadlinercsinstaller102
  VDeadlineRepositoryInstall x-. /opt/Thinkbox/DeadlineRepository10 .-x deadlinercsrunner[deadline-rcs-runner]
  VDeadlineClientInstall x-. /opt/Thinkbox/Deadline10 .-x deadlinercsrunner
  VDeadlineRepositoryrcsvarlibThinkboxDeadline10deadlineini{{"./DeadlineRepository/rcs/var/lib/Thinkbox/Deadline10/deadline.ini"}} -. "/var/lib/Thinkbox/Deadline10/deadline.ini" .-x deadlinercsrunner
  VDeadlineRepositoryrcsvarlibThinkboxDeadline10certcacertificatescrt{{"./DeadlineRepository/rcs/var/lib/Thinkbox/Deadline10/cert/ca-certificates.crt"}} -. "/var/lib/Thinkbox/Deadline10/cert/ca-certificates.crt" .-x deadlinercsrunner
  Vdeadlineinstaller -. /deadline_installer .-x deadlinewebserviceinstaller102[deadline-webservice-installer-10-2]
  VDeadlineClientWebserviceInstall{{"./DeadlineClientWebserviceInstall"}} x-. /opt/Thinkbox/Deadline10 .-x deadlinewebserviceinstaller102
  VDeadlineRepositoryInstall x-. /opt/Thinkbox/DeadlineRepository10 .-x deadlinewebserviceinstaller102
  VDeadlineRepositoryInstall x-. /opt/Thinkbox/DeadlineRepository10 .-x deadlinewebservicerunner[deadline-webservice-runner]
  VDeadlineClientWebserviceInstall x-. /opt/Thinkbox/Deadline10 .-x deadlinewebservicerunner
  VDeadlineRepositoryrcsvarlibThinkboxDeadline10deadlineini -. "/var/lib/Thinkbox/Deadline10/deadline.ini" .-x deadlinewebservicerunner
  VDeadlineRepositoryrcsvarlibThinkboxDeadline10certcacertificatescrt -. "/var/lib/Thinkbox/Deadline10/cert/ca-certificates.crt" .-x deadlinewebservicerunner
  deadlinercsinstaller102 --> deadlinerepositoryinstaller102
  deadlinercsrunner --> deadlinercsinstaller102
  deadlinerepositoryinstaller102 --> mongodb102
  deadlinewebserviceinstaller102 --> deadlinerepositoryinstaller102
  deadlinewebservicerunner --> deadlinewebserviceinstaller102
  filebrowser --> mongodb102
  mongoexpress --> mongodb102
  mongodb102 -.- mongodb[/mongodb/]
  mongoexpress -.- mongodb
  deadlinerepositoryinstaller102 -.- mongodb
  deadlinercsinstaller102 -.- mongodb
  deadlinercsrunner -.- mongodb
  deadlinewebserviceinstaller102 -.- mongodb
  deadlinewebservicerunner -.- mongodb
  mongodb102 -.- repository[/repository/]
  filebrowser -.- repository
  deadlinerepositoryinstaller102 -.- repository
  deadlinercsinstaller102 -.- repository
  deadlinercsrunner -.- repository
  deadlinewebserviceinstaller102 -.- repository
  deadlinewebservicerunner -.- repository

  classDef volumes fill:#fdfae4,stroke:#867a22
  class VtestdataoptThinkboxDeadlineDatabase10mongodataLOCAL,VtestdataoptThinkboxDeadlineDatabase10mongodataLOCAL,VtestdataoptThinkboxDeadlineDatabase10mongodataLOCAL,Vnfs,Vfilebrowserfilebrowserdb,Vfilebrowserfilebrowserjson,Vdeadlineinstaller,VDeadlineRepositoryInstall,Vdeadlineinstaller,VDeadlineRepositoryInstall,VDeadlineClientInstall,VDeadlineRepositoryInstall,VDeadlineClientInstall,VDeadlineRepositoryrcsvarlibThinkboxDeadline10deadlineini,VDeadlineRepositoryrcsvarlibThinkboxDeadline10certcacertificatescrt,Vdeadlineinstaller,VDeadlineClientWebserviceInstall,VDeadlineRepositoryInstall,VDeadlineRepositoryInstall,VDeadlineClientWebserviceInstall,VDeadlineRepositoryrcsvarlibThinkboxDeadline10deadlineini,VDeadlineRepositoryrcsvarlibThinkboxDeadline10certcacertificatescrt volumes
  classDef nets fill:#fbfff7,stroke:#8bc34a
  class mongodb,repository nets
