services:
  # Service Overrides for services:
  # https://github.com/ynput/ayon-docker/blob/main/docker-compose.yml
  #
  # https://docs.docker.com/compose/how-tos/multiple-compose-files/include/
  postgres:
    container_name: ayon-postgres-10-2
    hostname: ayon-postgres-10-2
    domainname: farm.evil
    networks:
      - repository
      - mongodb
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/data/share/nfs/databases/ayon/postgresql/data:/var/lib/postgresql/data"

  redis:
    container_name: ayon-redis-10-2
    hostname: ayon-redis-10-2
    domainname: farm.evil
    networks:
      - repository
      - mongodb

  server:
    container_name: ayon-server-10-2
    hostname: ayon-server-10-2
    domainname: farm.evil
    networks:
      - repository
      - mongodb
    ports:
    - "${AYON_PORT_HOST}:${AYON_PORT_CONTAINER}"
