__all__ = [
    "DOCKER_USE_CACHE",
    "MONGODB_INSIDE_CONTAINER",
    "KITSUDB_INSIDE_CONTAINER",
    "BUILD_FROM_GOOGLE_DRIVE_10_2",
]


DOCKER_USE_CACHE = False
MONGODB_INSIDE_CONTAINER = False
KITSUDB_INSIDE_CONTAINER = False
BUILD_FROM_GOOGLE_DRIVE_10_2 = False
