openstudiolandscapes__repository_root: "{REPOSITORY_ROOT}"  # maybe use GIT_ROOT?
openstudiolandscapes__configstore_root: "~/.config/OpenStudioLandscapes/config-store"

openstudiolandscapes__domain_lan: "openstudiolandscapes.lan"
#openstudiolandscapes__domain_wan: "openstudiolandscapes.cloud-ip.cc"
#
#openstudiolandscapes__su_method: "su"
#
##openstudiolandscapes__docker_config: "local_registry"
#openstudiolandscapes__docker_config: "localhost"
#
#openstudiolandscapes__attach_pangolin_site_to_compose_scope: true



openstudiolandscapes__docker_config:
  use_registry: true
  no_cache: true
  # If `use_registry` is false,
  # `docker_registry_config` values are ignored.
  docker_registry_config:
    docker_push: true  # Is this necessary?
    docker_pull: true  # Is this necessary?
    # docker_use_local: false  # What is this for?
    docker_repository_name: "OpenStudioLandscapes"  # will be converted to all lowercase
#    docker_registry_access: "public"
#    docker_registry_protocol: "https"
    docker_registry_fqdn: "registry.openstudiolandscapes.lan"
    docker_registry_port: 5000
    docker_registry_username: "registry-user"
    docker_registry_password: "registry-password"

# For testing
illegal_option: 1234
