%%{init: {'theme': 'dark'}}%%
flowchart TB
  Vetclocaltime{{/etc/localtime}} -. /etc/localtime .-x postgres[(postgres)]
  Vdb([db]) x-. /var/lib/postgresql/data .-x postgres
  Vaddons{{"./addons"}} x-. /addons .-x server
  Vstorage{{"./storage"}} x-. /storage .-x server
  Vetclocaltime -. /etc/localtime .-x server
  server --> postgres
  server --> redis[(redis)]
  P0((5000)) -.-> server

  classDef volumes fill:#0f544e,stroke:#23968b
  class Vetclocaltime,Vdb,Vaddons,Vstorage,Vetclocaltime volumes
  classDef ports fill:#5a5757,stroke:#b6c2ff
  class P0 ports
