%%{init: {'theme': 'dark'}}%%
flowchart TB
  Vetclocaltime{{/etc/localtime}} -. /etc/localtime .-x postgres[(postgres)]
  Vdatasharenfsdatabasesayonpostgresqldata{{/data/share/nfs/databases/ayon/postgresql/data}} x-. /var/lib/postgresql/data .-x postgres
  postgres -.- repository[/repository/]
  redis[(redis)] -.- repository
  server -.- repository
  postgres -.- mongodb[/mongodb/]
  redis -.- mongodb
  server -.- mongodb

  classDef volumes fill:#0f544e,stroke:#23968b
  class Vetclocaltime,Vdatasharenfsdatabasesayonpostgresqldata volumes
  classDef nets fill:#3f51b5,stroke:#81B1DB
  class repository,mongodb nets
