%%{init: {'theme': 'dark'}}%%
flowchart TB
  Vpostgrespostgresqlconf{{"./postgres/postgresql.conf"}} -. "/etc/postgresql/14/main/postgresql.conf" .-x kitsu102[kitsu-10-2]
  Vdatasharenfs{{/data/share/nfs}} x-. /data/share/nfs .-x kitsu102
  Vdatasharenfs x-. /nfs .-x kitsu102
  P0((5432)) -.-> kitsu102

  classDef volumes fill:#0f544e,stroke:#23968b
  class Vpostgrespostgresqlconf,Vdatasharenfs,Vdatasharenfs volumes
  classDef ports fill:#5a5757,stroke:#b6c2ff
  class P0 ports
