# 1)
# Launch Harbor
# sudo docker compose --file ../.landscapes/.harbor/bin/docker-compose.yml --project-name openstudiolandscapes-harbor up --remove-orphans
# sudo docker compose --file ../.landscapes/.harbor/bin/docker-compose.yml --project-name openstudiolandscapes-harbor down
#
# I tried "include" but Harbor needs "sudo" whereas openstudiolandscapes does not.
# This lead to problems, hence, launch them separately.
#include:
#  - path:
#      - ../.landscapes/.harbor/bin/docker-compose.yml

# 2)
# Launch openstudiolandscapes
# docker compose --file docker-compose.yml --project-name openstudiolandscapes up --remove-orphans
# docker compose --file docker-compose.yml --project-name openstudiolandscapes down


networks:
  openstudiolandscapes:
    name: network_openstudiolandscapes

services:
  postgres-dagster:
    container_name: openstudiolandscapes-postgres
    domainname: farm.evil
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
    hostname: openstudiolandscapes-postgres.farm.evil
    image: docker.io/postgres
    networks:
      - openstudiolandscapes
    restart: unless-stopped
    volumes:
      - ./.volumes/postgres-dagster/postgres:/var/lib/postgresql/data:rw
  dagster:
    container_name: openstudiolandscapes-dagster-postgres
    domainname: farm.evil
    hostname: openstudiolandscapes-dagster-postgres.farm.evil
    image: docker.io/michimussato/openstudiolandscapes:latest
    command:
      - "nox"
      - "--session"
      - "dagster_postgres"
    depends_on:
      - postgres-dagster
#      - log
#      - registry
#      - registryctl
#      - postgresql
#      - core
#      - portal
#      - jobservice
#      - redis
#      - proxy
    networks:
      - openstudiolandscapes
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./.volumes/.landscapes:/home/openstudiolandscapes/git/repos/OpenStudioLandscapes/.landscapes:rw
      - ./.volumes/dagster:/home/openstudiolandscapes/git/repos/OpenStudioLandscapes/.dagster-postgres:rw
      # sudo ln -sfn $HOME /home/openstudiolandscapes
      - ./.volumes/dagster:/home/openstudiolandscapes/git/repos/OpenStudioLandscapes/.dagster-postgres:rw
      # https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/
      # Access to host socket
      - /var/run/docker.sock:/var/run/docker.sock:rw
      # Access to host cache
      # necessary? socket only?
      - /var/lib/docker:/var/lib/docker:rw
