FROM michimussato/client_image_10_2:latest AS generic_runner_10_2
LABEL authors="michimussato@gmail.com"

SHELL ["/bin/bash", "-c"]

ENTRYPOINT ["deadline-wrapper-10-2", "-vv", "run"]

CMD ["--help"]
