networks:
  postgres-dagster:
    name: network_postgres-dagster
services:
  postgres-dagster:
    container_name: postgres-dagster
    domainname: farm.evil
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
    hostname: postgres-dagster.farm.evil
    image: docker.io/postgres
    networks:
    - postgres-dagster
    ports:
    - 2345:5432
    restart: unless-stopped
    volumes:
    - /home/michael/git/repos/OpenStudioLandscapes/.dagster-postgres/.postgres:/var/lib/postgresql/data:rw
